// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAccount = "account"

// Account mapped from table <account>
type Account struct {
	ID         uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Password   string         `gorm:"column:password;not null" json:"password"`
	SignedUpAt time.Time      `gorm:"column:signed_up_at;not null;default:CURRENT_TIMESTAMP" json:"signed_up_at"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
