// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameComment = "comments"

// Comment mapped from table <comments>
type Comment struct {
	ID        uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	PostID    uint32         `gorm:"column:post_id;not null;index:idx_comments_post_id,priority:1" json:"post_id"`
	UserID    uint32         `gorm:"column:user_id;not null;index:idx_comments_user_id,priority:1" json:"user_id"`
	ParentID  *uint32        `gorm:"column:parent_id;index:idx_comments_parent_id,priority:1" json:"parent_id"`
	Content   string         `gorm:"column:content;not null" json:"content"`
	LikeCount int32          `gorm:"column:like_count;not null" json:"like_count"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
