// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCommentLike = "comment_likes"

// CommentLike mapped from table <comment_likes>
type CommentLike struct {
	ID        uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CommentID uint32         `gorm:"column:comment_id;not null;uniqueIndex:unique_comment_user_like,priority:1;index:idx_comment_likes_comment_id,priority:1" json:"comment_id"`
	UserID    uint32         `gorm:"column:user_id;not null;uniqueIndex:unique_comment_user_like,priority:2;index:idx_comment_likes_user_id,priority:1" json:"user_id"`
}

// TableName CommentLike's table name
func (*CommentLike) TableName() string {
	return TableNameCommentLike
}
