// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePost = "posts"

// Post mapped from table <posts>
type Post struct {
	ID           uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at;not null;index:idx_posts_created_at,priority:1;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID       uint32         `gorm:"column:user_id;not null;index:idx_posts_user_id,priority:1" json:"user_id"`
	Title        string         `gorm:"column:title;not null" json:"title"`
	Content      string         `gorm:"column:content;not null" json:"content"`
	ImageURL     *string        `gorm:"column:image_url" json:"image_url"`
	IsPublic     bool           `gorm:"column:is_public;not null;index:idx_posts_is_public,priority:1;default:1" json:"is_public"`
	ViewCount    int32          `gorm:"column:view_count;not null" json:"view_count"`
	LikeCount    int32          `gorm:"column:like_count;not null" json:"like_count"`
	CommentCount int32          `gorm:"column:comment_count;not null" json:"comment_count"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
