// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostLike = "post_likes"

// PostLike mapped from table <post_likes>
type PostLike struct {
	ID        uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	PostID    uint32         `gorm:"column:post_id;not null;uniqueIndex:unique_post_user_like,priority:1;index:idx_post_likes_post_id,priority:1" json:"post_id"`
	UserID    uint32         `gorm:"column:user_id;not null;uniqueIndex:unique_post_user_like,priority:2;index:idx_post_likes_user_id,priority:1" json:"user_id"`
}

// TableName PostLike's table name
func (*PostLike) TableName() string {
	return TableNamePostLike
}
