// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserFacebookLogin = "user_facebook_logins"

// UserFacebookLogin mapped from table <user_facebook_logins>
type UserFacebookLogin struct {
	ID        uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID    uint32         `gorm:"column:user_id;not null;index:user_id,priority:1" json:"user_id"`
	FbID      string         `gorm:"column:fb_id;not null" json:"fb_id"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	Name      string         `gorm:"column:name;not null" json:"name"`
}

// TableName UserFacebookLogin's table name
func (*UserFacebookLogin) TableName() string {
	return TableNameUserFacebookLogin
}
