// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserFollow = "user_follows"

// UserFollow mapped from table <user_follows>
type UserFollow struct {
	ID          uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	FollowerID  uint32         `gorm:"column:follower_id;not null;uniqueIndex:unique_follow_relationship,priority:1;index:idx_user_follows_follower_id,priority:1" json:"follower_id"`
	FollowingID uint32         `gorm:"column:following_id;not null;uniqueIndex:unique_follow_relationship,priority:2;index:idx_user_follows_following_id,priority:1" json:"following_id"`
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
