// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           uint32         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	AccountID    uint32         `gorm:"column:account_id;not null;index:account_id,priority:1" json:"account_id"`
	Email        string         `gorm:"column:email;not null" json:"email"`
	Name         string         `gorm:"column:name;not null" json:"name"`
	IsBanned     bool           `gorm:"column:is_banned;not null" json:"is_banned"`
	IsFirstLogin bool           `gorm:"column:is_first_login;not null" json:"is_first_login"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
